config/routes.rb
  ProjectSoftlineinformatica::Application.routes.draw do
    devise_for :users, :path => "auth", 
    :path_names =>{:sign_in => 'login', 
      :sign_out => 'logout', 
      :password => 'secret', 
      :confirmation => 'verification',
      :unlock => 'unblock'},

      :controllers => {:sessions => "sessions"} do
        get 'auth/logout' => 'sessions#destroy', :as => :destroy_user_session
      end

  root :to => 'welcome#index'
  match 'test' =>  'welcome#test', :via => :get, :as => :test

  resources :users
  resources :companies do
    resources :soluctions, :except => [:index,:new]
  end

  resources :contacts, :except => [:edit, :update]

  match 'new_soluction' => 'soluctions#new', :via => :get, :as => :new_soluction
  match 'create_soluction' => 'soluctions#create_soluction', :via => :post, :as =>  :create_soluction
  match 'index_soluctions' => 'soluctions#index_soluctions', :via => :get, :as => :index_soluctions
  match 'contacts/get_states/:id' => 'contacts#get_states', :via => :get
  match 'information_contacts' => 'contacts#information',:via => :get, :as => :information_contacts

end

app/models/soluction.rb
class Soluction < ActiveRecord::Base

	#Attr_accessible
	attr_accessible :description, :title, :company_id

	#Validations
	validates :description, :presence => true, :allow_blank => false
	validates :title, :presence => true, :allow_blank => false
	validates :company_id, :presence => true

	#Associations
	belongs_to :company

end

app/controllers/soluctions_controller.rb
# -*- coding: utf-8 -*-
class SoluctionsController < ApplicationController

	before_filter :authenticate_user!, :except => [:index_soluctions]

	def index_soluctions
		@soluctions = Soluction.all
	end

	def new
		@companies = Company.all
		@soluction = Soluction.new
	end

	def create
		@soluction = Soluction.new(params[:soluction])
		if @soluction.save
			flash[:notice] = "Serviço inserido com sucesso!"
		else
			flash[:notice] = "Falha ao cadastrar o serviço!"
		end
	end

	def create_soluction
		@soluction = Soluction.new(:company_id => params[:company_id], :title => params[:title],
		:description => params[:description])

		if @soluction.save
			redirect_to @soluction.company
		else
			render :action => :new
		end
	end

	def edit
		@soluction = Soluction.find(params[:id])
	end

	def update
		@soluction = Soluction.find(params[:id])
		if @soluction.update_attributes(params[:soluction])
			flash[:notice] = "Serviço atualizado com sucesso!"
		else
			flash[:notice] = "Serviço não foi atualizado, ocorreu um erro inesperado!"
		end
	end

	def destroy
		@soluction = Soluction.find(params[:id])
		flash[:notice] = @soluction.destroy ? "Serviço excluído com sucesso!" : "Falha na exclusão do registro!" 
	end
end

app/views/soluctions/_form.html.erb
<hr>
<h4>Novo Serviço</h4>

<%= form_for([company, soluction], :remote => true) do |f|%>

<%= f.hidden_field :company_id, :value => company.id %>

<%= f.label :title, "Título" %>
<%= f.text_field :title %>

<%= f.label :description, "Descrição" %>
<%= f.text_area :description, :class => "span7" %>

<div class="actions">
	<%= f.submit "Salvar", :class => "btn btn-primary" %>
</div>


<% end %>

app/views/soluctions/_index.html.erb
<% if soluctions.any? %>
<% soluctions.each do |s| %>
<table class="table table-bordered">
	<tr>
		<td>
			<div id='solucao_<%= s.id %>'>
				<h2><%= s.title %></h2>
				<p><%= s.description %></p>
				<% if user_signed_in? %>
				<%= link_to "Editar", edit_company_soluction_path(s.company, s), :class => "btn btn-warning", :remote => true %> 
				<%= link_to "Excluir", [s.company, s], :method => :delete, :class => "btn btn-inverse", :remote => true, :confirm => "Deseja excluir esse registro?" %>
				<% end %>
			</div>
		</td>
	</tr>
</table>

<% end %>

<% else %>
<div class="alert">
	Não há soluções cadastradas!
</div>

<% end%>

app/views/soluctions/create.js.erb
<% if @soluction.persisted? %>
$("#lista_solucao").html("<%= j render :partial => 'soluctions/index', :locals =>{:soluctions => @soluction.company.soluctions} %>");
$("#notice").prepend("<%= j notice %>");
$("#nova_solucao").html("<%= j render :partial => 'soluctions/form', :locals =>{:soluction => Soluction.new, :company => @soluction.company} %>");
<% else %>
$("#nova_solucao").html("<%= j render :partial => 'soluctions/form', :locals => {:soluction => Soluction.new, :company => @soluction.company} %>");
<% end %>

app/views/soluctions/destroy.js.erb
<% if @soluction.destroyed? %>
$("#solucao_<%= @soluction.id %>").remove();
<% else %>
$("#notice").prepend("<%= j notice %>");
<% end %>

app/views/soluctions/edit.js.erb
$("#nova_solucao").html("<%= j render :partial => 'soluctions/form', :locals => {:soluction => @soluction, :company => @soluction.company} %>");
$("html, body").animate({scrolltop:$("#nova_solucao").offset().top});

app/views/soluctions/index_soluctions.html.erb
<% if user_signed_in? == false %>
<!-- /.header -->
<section class="page-title-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-6 page-title">
                <h4>Serviços</h4>
            </div>
            <!-- /.page-title -->
            <div class="col-xs-6 hidden-xs breadcrumb-wrapper">
                <ol class="breadcrumb pull-right">
                    <li><%=link_to "Home", root_path %></li>
                    <li><%=link_to "A Empresa", companies_path %></li>
                    <li class="active">Serviços</li>
                </ol>
            </div>
            <!-- /.breadcrumb-wrapper -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container -->
</section>
<% end %>

<div class="container">
    <hr>
    <% if @soluctions.any? %>
    <% @soluctions.each do |soluction| %>
    <% if soluction.title == "Suporte Técnico" %>
    <hr>
    <% end %>
    <table class="table table-bordered">
      <tr>
         <td>
            <h3><%= soluction.title %></h3>
            <p><b><%= soluction.description %></b></p>
        </td>
    </tr>
</table>
<% end %>
<% else %>
<div class="alert">
  Não há serviços cadastradas!
</div>
<% end %>
</div>

app/views/soluctions/new.html.erb
</hr>
<h4>Novo Serviço</h4>

<%=form_tag(create_soluction_path) do %>

<%= label_tag :company_id, "Des. Empresa" %>
<%= select_tag :company_id, options_from_collection_for_select(@companies, :id, :title, @soluction.company_id) %>

<%= label_tag :title, "Título" %>
<%= text_field_tag :title, @soluction.title %>

<%= label_tag :description, "Descrição" %>
<%= text_area_tag :description, @soluction.description, :rows => 10,:class => "span7" %>

 
<div class="actions">
	<%= submit_tag "Salvar", :class => "btn btn-primary" %>
	<%= link_to "Voltar", root_path, :class => "btn"%>
</div>
<% end %>

app/views/soluctions/update.js.erb
<% if @soluction.valid? %>
$("#lista_solucao").html("<%= j render :partial => 'soluctions/index', :locals =>{:soluctions => @soluction.company.soluctions} %>");
$("#notice").prepend("<%= j notice %>");
$("#nova_solucao").html("<%= j render :partial => 'soluctions/form', :locals =>{:soluction => Soluction.new, :company => @soluction.company} %>");
<% else %>
$("#nova_solucao").html("<%= j render :partial => 'soluctions/form', :locals => {:soluction => Soluction.new, :company => @soluction.company} %>");
<% end %>