config/routes.rb
  ProjectSoftlineinformatica::Application.routes.draw do
    devise_for :users, :path => "auth", 
    :path_names =>{:sign_in => 'login', 
      :sign_out => 'logout', 
      :password => 'secret', 
      :confirmation => 'verification',
      :unlock => 'unblock'},

      :controllers => {:sessions => "sessions"} do
        get 'auth/logout' => 'sessions#destroy', :as => :destroy_user_session
      end

  root :to => 'welcome#index'
  match 'test' =>  'welcome#test', :via => :get, :as => :test

  resources :users
  resources :companies do
    resources :soluctions, :except => [:index,:new]
  end

  resources :contacts, :except => [:edit, :update]

  match 'new_soluction' => 'soluctions#new', :via => :get, :as => :new_soluction
  match 'create_soluction' => 'soluctions#create_soluction', :via => :post, :as =>  :create_soluction
  match 'index_soluctions' => 'soluctions#index_soluctions', :via => :get, :as => :index_soluctions
  match 'contacts/get_states/:id' => 'contacts#get_states', :via => :get
  match 'information_contacts' => 'contacts#information',:via => :get, :as => :information_contacts

end

app/views/shared/_footer.html.erb
<footer>
	<p>&copy; Todos os direitos reservados. Desenvolvido por www.softlineinformatica.com </p>
</footer>

app/views/shared/_menu_top.html.erb
        
        <header class="header">
            <nav class="navbar navbar-default" role="navigation">
                <div class="container">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <a class="navbar-fixed" href="#" ><%=link_to (image_tag 'softline.jpg'), root_path %></a>
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>

                        </button>
                        
                    </div>
                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse navbar-ex1-collapse">

                        <ul class="nav navbar-nav">
                            <li class="active"><%=link_to "Home", root_path %></li>
                            <li class="dropdown">
                              <%=link_to "A Empresa", companies_path, :class => "dropdown-toggle" %>
                            </li>
                            <li class="dropdown">
                                  <%=link_to "Serviços", index_soluctions_path, :class => "dropdown-toggle" %>
                            </li>
                            <li class="dropdown">
                                <%=link_to "Contato", information_contacts_path, :class => "dropdown-toggle" %>
                            </li>
                            <li class="dropdown">
                                <%=link_to "Fale Conosco", new_contact_path, :class => "dropdown-toggle" %>
                            </li>
                        </ul>
                        <!-- /.nav -->
                    </div>
                    <!-- /.navbar-collapse -->
                </div>
                <!-- /.container -->
            </nav>
            <!-- /.navbar -->
        </header>
        <!-- /.header -->
       

app/views/shared/_other_options.html.erb
<section class="our-services">
    <div class="container">
        <hr>
        <div class="row">
            <div class="col-md-4 ">
                <div class="service">
                    <span class="service-icon">
                        <%=link_to (fa_icon "laptop"), companies_path, :style=>'color:#FFFFFF;' %>
                    </span>
                    <h4>A Empresa</h4>
                    <p>A Softline Informática oferece um sistema...</p>
                </div>
            </div>
            <div class="col-md-4">
                <div class="service">
                    <span class="service-icon">
                        <%=link_to (fa_icon "gear"), index_soluctions_path, :style=>'color:#FFFFFF;' %>
                    </span>
                    <h4>Serviços</h4>
                    <p>A Softline provem diversos serviços</p>
                </div>
            </div>
            <div class="col-md-4">
                <div class="service">
                    <span class="service-icon">
                        <%= link_to (fa_icon "envelope-o"), new_contact_path,:style=>'color:#FFFFFF;' %>
                    </span>
                    <h4>Fale Conosco</h4>
                    <p>Procure entrar em contato conosco</p>
                </div>
            </div>
        </div>
        <hr>
    </div>
    <!-- /.container -->
</section>