config/routes.rb
  ProjectSoftlineinformatica::Application.routes.draw do
    devise_for :users, :path => "auth", 
    :path_names =>{:sign_in => 'login', 
      :sign_out => 'logout', 
      :password => 'secret', 
      :confirmation => 'verification',
      :unlock => 'unblock'},

      :controllers => {:sessions => "sessions"} do
        get 'auth/logout' => 'sessions#destroy', :as => :destroy_user_session
      end

  root :to => 'welcome#index'
  match 'test' =>  'welcome#test', :via => :get, :as => :test

  resources :users
  resources :companies do
    resources :soluctions, :except => [:index,:new]
  end

  resources :contacts, :except => [:edit, :update]

  match 'new_soluction' => 'soluctions#new', :via => :get, :as => :new_soluction
  match 'create_soluction' => 'soluctions#create_soluction', :via => :post, :as =>  :create_soluction
  match 'index_soluctions' => 'soluctions#index_soluctions', :via => :get, :as => :index_soluctions
  match 'contacts/get_states/:id' => 'contacts#get_states', :via => :get
  match 'information_contacts' => 'contacts#information',:via => :get, :as => :information_contacts

end

app/views/shared_admin/_menu_top.html.erb
<div class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".navbar-inverse-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%=link_to "Softline Informática Ltda", root_path, :class => "brand" %>
      <div class="nav-collapse collapse navbar-inverse-collapse">
        <ul class="nav">
          <li class="active"><a href="#" class="dropdown-toggle" data-toggle="dropdown">A Empresa <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><a href="#"><%= link_to "Ins. Descrição", new_company_path %></a></li>
              <li><a href="#"><%= link_to "Visualizar", companies_path %></a></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Serviços <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><a href="#"><%= link_to "Inserir", new_soluction_path  %></a></li>
              <li><a href="#"><%= link_to "Visualizar/Alterar", companies_path %></a></li>
            </ul>
          </li>
        </ul>
        <ul class="nav pull-right">
          <li class="divider-vertical"></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Conta <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><% if user_signed_in? %>
                <a href="#"><%= link_to current_user.email, current_user %></a>
                <% else %>
                <%= link_to "login", new_user_session_path %>
                <% end %>
              </li>
              <li><a href="#"><%= link_to "Contatos", contacts_path %></a></li>
              <li><a href="#"><%= link_to "Sair", destroy_user_session_path, :method => :delete %></a></li>
              <li class="divider"></li>
              <li><a href="#">Esse link não faz nada</a></li>
            </ul>
          </li>
        </ul>
      </div><!-- /.nav-collapse -->
    </div>
  </div><!-- /navbar-inner -->
</div><!-- /navbar -->